apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tz49qek6t-go 
  janus-idp.io/tekton: tz49qek6t-go
  backstage.io/kubernetes-id: tz49qek6t-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tz49qek6t-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml